import { supabase } from "@/lib/supabaseClient"
import { currentUser } from "@clerk/nextjs/server"

export interface UserData {
  id: string
  clerk_user_id: string
  email?: string
  first_name?: string
  last_name?: string
  image_url?: string
}

/**
 * Creates or updates a user in Supabase when they sign in with Clerk
 */
export async function createOrUpdateUser(): Promise<UserData | null> {
  try {
    const user = await currentUser()

    if (!user) {
      throw new Error("No authenticated user found")
    }

    const userData: UserData = {
      id: user.id, // This will be generated by Supabase if not provided
      clerk_user_id: user.id,
      email: user.emailAddresses[0]?.emailAddress,
      first_name: user.firstName || undefined,
      last_name: user.lastName || undefined,
      image_url: user.imageUrl,
    }

    // Check if user already exists
    const { data: existingUser } = await supabase
      .from("users")
      .select("*")
      .eq("clerk_user_id", user.id)
      .single()

    if (existingUser) {
      // Update existing user
      const { data: updatedUser, error } = await supabase
        .from("users")
        .update({
          email: userData.email,
          first_name: userData.first_name || undefined,
          last_name: userData.last_name || undefined,
          image_url: userData.image_url,
          updated_at: new Date().toISOString(),
        })
        .eq("clerk_user_id", user.id)
        .select()
        .single()

      if (error) {
        console.error("Error updating user:", error)
        return null
      }

      return updatedUser
    } else {
      // Create new user
      const { data: newUser, error } = await supabase
        .from("users")
        .insert([userData])
        .select()
        .single()

      if (error) {
        console.error("Error creating user:", error)
        return null
      }

      return newUser
    }
  } catch (error) {
    console.error("Error in createOrUpdateUser:", error)
    return null
  }
}

/**
 * Gets the current user from Supabase based on Clerk authentication
 */
export async function getCurrentUser(): Promise<UserData | null> {
  try {
    const user = await currentUser()

    if (!user) {
      return null
    }

    const { data: supabaseUser, error } = await supabase
      .from("users")
      .select("*")
      .eq("clerk_user_id", user.id)
      .single()

    if (error) {
      console.error("Error fetching user:", error)
      return null
    }

    return supabaseUser
  } catch (error) {
    console.error("Error in getCurrentUser:", error)
    return null
  }
}
