import Link from "next/link"
import { LuHome } from "react-icons/lu"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen flex justify-center items-center realtive">
        <div className="absolute top-5 left-5">
          <Link href="/" className="flex items-center gap-2" prefetch={false}>
            <LuHome size={20} />
            <span className="font-bold">Home Champion</span>
          </Link>
        </div>
        {children}
      </body>
    </html>
  )
}
