/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/orPmBX0r4DB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Link from "next/link"

export default function AboutAppInfo() {
  return (
    <div className="w-full  mx-auto">
      <div className="bg-base-200 rounded-lg shadow-lg overflow-hidden">
        <div className="px-6 py-8">
          <h2 className="text-2xl font-bold mb-4">About Our App</h2>
          <p className="text-muted-foreground mb-6">
            Our mobile app is designed to simplify your daily tasks and help you
            stay organized. With a clean and intuitive interface, you can easily
            manage your to-do lists, set reminders, and track your progress.
          </p>
          <div className="bg-muted rounded-lg p-6">
            <h3 className="text-lg font-bold mb-4">Meet the Developer</h3>
            <div className="flex items-center mb-4">
              <Avatar className="w-12 h-12 mr-4">
                <AvatarFallback>AK</AvatarFallback>
              </Avatar>
              <div>
                <h4 className="text-base font-bold">Amr Khaled</h4>
                <p className="text-sm text-muted-foreground">Web Developer</p>
              </div>
            </div>
            <p className="text-muted-foreground mb-4">
              John is a passionate app developer with a keen eye for design and
              user experience. He has been creating mobile apps for over 5 years
              and is always striving to push the boundaries of what&#39;s
              possible.
            </p>
            <div className="flex gap-4">
              <Link
                href="#"
                className="text-primary hover:underline"
                prefetch={false}
              >
                <TwitterIcon className="w-5 h-5" />
              </Link>
              <Link
                href="#"
                className="text-primary hover:underline"
                prefetch={false}
              >
                <GitlabIcon className="w-5 h-5" />
              </Link>
              <Link
                href="#"
                className="text-primary hover:underline"
                prefetch={false}
              >
                <LinkedinIcon className="w-5 h-5" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function GitlabIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}

function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}

function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
